# Generated by Django 5.1.7 on 2025-04-10 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='added_at',
            new_name='created_at',
        ),
    ]
