# Generated by Django 5.1.7 on 2025-04-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_notification_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_message', 'Nouveau message'), ('new_order', 'Nouvelle commande'), ('order_details', 'Détails de la commande'), ('order_delivered', 'Commande livrée')], max_length=50),
        ),
    ]
