# Generated by Django 5.1.7 on 2025-03-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('product', 'Product'), ('blog', 'Blog')], default='product', max_length=20),
        ),
    ]
