# Generated by Django 5.1.7 on 2025-04-12 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_alter_cartitem_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
