# Generated by Django 5.1.7 on 2025-04-12 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_alter_review_unique_together_alter_review_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount percentage (0-100)', max_digits=5),
        ),
    ]
