# Generated by Django 5.1.7 on 2025-04-09 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_image'),
        ('ecommerce', '0008_category_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(limit_choices_to={'category_type': 'blog'}, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié')], default='published', max_length=20),
        ),
        migrations.DeleteModel(
            name='BlogCategory',
        ),
    ]
