# Generated by Django 5.1.7 on 2025-04-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_updated_at_order_delivery_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_option',
        ),
        migrations.AddField(
            model_name='order',
            name='card_cvv',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='card_expiry',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='card_holder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='card_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('orange_money', 'Orange Money'), ('mtn_money', 'Wave'), ('card', 'Carte Bancaire'), ('cod', 'Paiement à la livraison')], default='cod', max_length=20),
        ),
    ]
